project:
  type: website

website:
  title: Brady Earley

  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: about.qmd
        text: About

      - href: research/index.qmd
        text: Research

      - href: data_and_code/index.qmd
        text: Data and Code

      - href: writing/index.qmd
        text: Writing

      - href: cv.pdf
        text: CV

    right:
      - icon: github
        href: https://github.com/bradyearley

      - icon: linkedin
        href: https://linkedin.com/in/brady-earley/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
